[package]
name = "baik"
version = "10.0.0"
authors = ["anak10thn <anak10thn@gmail.com>"]
edition = "2018"

[dependencies]
pest = "2.1.0"
pest_derive = "2.1.0"
serde_json = "1.0.39"
serde = "1.0.89"

[[bin]]
name = "baik"
doc = false